version: '3'

services:
  observer-0:
    image: ${OBSERVER_IMAGE}
    ports:
      - "8080:8080"
      - "10000:37373"
    volumes:
      - ${DATA_FOLDER}/node-0/logs:/data/logs
      - ${DATA_FOLDER}/node-0/db:/data/db
      - ${KEYS_FOLDER}:/keys
    command: --destination-shard-as-observer=0 --validator-key-pem-file=/keys/0.pem
    networks:
      elrond-rosetta-squad:
        ipv4_address: 10.0.0.10

  observer-1:
    image: ${OBSERVER_IMAGE}
    ports:
      - "8081:8080"
      - "10001:37373"
    volumes:
      - ${DATA_FOLDER}/node-1/logs:/data/logs
      - ${DATA_FOLDER}/node-1/db:/data/db
      - ${KEYS_FOLDER}:/keys
    command: --destination-shard-as-observer=1 --validator-key-pem-file=/keys/1.pem
    networks:
      elrond-rosetta-squad:
        ipv4_address: 10.0.0.11

  observer-2:
    image: ${OBSERVER_IMAGE}
    ports:
      - "8082:8080"
      - "10002:37373"
    volumes:
      - ${DATA_FOLDER}/node-2/logs:/data/logs
      - ${DATA_FOLDER}/node-2/db:/data/db
      - ${KEYS_FOLDER}:/keys
    command: --destination-shard-as-observer=2 --validator-key-pem-file=/keys/2.pem
    networks:
      elrond-rosetta-squad:
        ipv4_address: 10.0.0.12

  observer-metachain:
    image: ${OBSERVER_IMAGE}
    ports:
      - "8083:8080"
      - "10003:37373"
    volumes:
      - ${DATA_FOLDER}/node-metachain/logs:/data/logs
      - ${DATA_FOLDER}/node-metachain/db:/data/db
      - ${KEYS_FOLDER}:/keys
    command: --destination-shard-as-observer=metachain --validator-key-pem-file=/keys/metachain.pem
    networks:
      elrond-rosetta-squad:
        ipv4_address: 10.0.0.13

  proxy:
    image: ${PROXY_IMAGE}
    ports:
      - "8090:8080"
    volumes:
      - ${DATA_FOLDER}/proxy/logs:/data/logs
    networks:
      elrond-rosetta-squad:
        ipv4_address: 10.0.0.20

  proxy-rosetta:
    image: ${PROXY_IMAGE}
    ports:
      - "8091:8080"
    volumes:
      - ${DATA_FOLDER}/proxy-rosetta/logs:/data/logs
    command: --rosetta
    networks:
      elrond-rosetta-squad:
        ipv4_address: 10.0.0.21

  proxy-rosetta-offline:
    image: ${PROXY_IMAGE}
    ports:
      - "8092:8080"
    volumes:
      - ${DATA_FOLDER}/proxy-rosetta-offline/logs:/data/logs
    command: --rosetta --offline --offline-config=/elrond/config/${OFFLINE_CONFIG}
    networks:
      elrond-rosetta-squad:
        ipv4_address: 10.0.0.22

networks:
  elrond-rosetta-squad:
    ipam:
      config:
        - subnet: 10.0.0.0/24
