# Credentials holds the list of username-pair pairs that allow access to certain endpoints.
# Please change these example values as they are just placeholders.
Credentials = [
    { Username = "example", Password = "example" },
    { Username = "example2", Password = "example2" }
]

[Hasher]
Type = "sha256"
