# Credentials holds the list of username-pair pairs that allow access to certain endpoints.
# The password represents the hashed value. In this examples, the password are the hashed usernames.
# Please change these example values as they are just placeholders.
Credentials = [
    { Username = "example", Password = "50d858e0985ecc7f60418aaf0cc5ab587f42c2570a884095a9e8ccacd0f6545c" },
    { Username = "example2", Password = "5fb1679e08674059b72e271d8902c11a127bb5301b055dc77fa03932ada56a56" }
]

[Hasher]
Type = "sha256"
