# API routes configuration for version v1.0
[APIPackages]

[APIPackages.actions]
Routes = [
    { Name = "/reload-observers", Open = true, Secured = true },
    { Name = "/reload-full-history-observers", Open = true, Secured = true }
]

[APIPackages.node]
Routes = [
    { Name = "/heartbeatstatus", Open = true, Secured = false },
]

[APIPackages.address]
Routes = [
    { Name = "/:address", Open = true, Secured = false },
    { Name = "/:address/balance", Open = true, Secured = false },
    { Name = "/:address/nonce", Open = true, Secured = false },
    { Name = "/:address/username", Open = true, Secured = false },
    { Name = "/:address/keys", Open = true, Secured = false },
    { Name = "/:address/key/:key", Open = true, Secured = false },
    { Name = "/:address/esdt", Open = true, Secured = false },
    { Name = "/:address/esdt/:tokenIdentifier", Open = true, Secured = false },
    { Name = "/:address/shard", Open = true, Secured = false },
    { Name = "/:address/transactions", Open = true, Secured = false }
]

[APIPackages.hyperblock]
Routes = [
    { Name = "/by-hash/:hash", Open = true, Secured = false },
    { Name = "/by-nonce/:nonce", Open = true, Secured = false }
]

[APIPackages.network]
Routes = [
    { Name = "/status/:shard", Open = true, Secured = false },
    { Name = "/economics", Open = true, Secured = false },
    { Name = "/config", Open = true, Secured = false }
]

[APIPackages.validator]
Routes = [
    { Name = "/statistics", Open = true, Secured = false }
]

[APIPackages.vm-values]
Routes = [
    { Name = "/hex", Open = true, Secured = false },
    { Name = "/string", Open = true, Secured = false },
    { Name = "/int", Open = true, Secured = false },
    { Name = "/query", Open = true, Secured = false }
]

[APIPackages.transaction]
Routes = [
    { Name = "/send", Open = true, Secured = false },
    { Name = "/simulate", Open = false, Secured = false },
    { Name = "/send-multiple", Open = true, Secured = false },
    { Name = "/send-user-funds", Open = true, Secured = false },
    { Name = "/cost", Open = true, Secured = false },
    { Name = "/:txhash", Open = true, Secured = false },
    { Name = "/:txhash/status", Open = true, Secured = false }
]

[APIPackages.block]
Routes = [
    { Name = "/:shard/by-nonce/:nonce", Open = true },
    { Name = "/:shard/by-hash/:hash", Open = true }
]

[APIPackages.block-atlas]
Routes = [
    { Name = "/:shard/:nonce", Open = true }
]
