version: '3'

services:
  observer-0:
    image: ${OBSERVER_IMAGE}
    ports:
      - "8080:8080"
      - "10000:37373"
    volumes:
      - ${DATA_FOLDER}/node-0/logs:/data/logs
      - ${DATA_FOLDER}/node-0/db:/data/db
      - ${KEYS_FOLDER}:/keys
    command: --destination-shard-as-observer=0 --validator-key-pem-file=/keys/0.pem
    networks:
      elrond-rosetta:
        ipv4_address: 10.0.0.10

  rosetta:
    image: ${ROSETTA_IMAGE}
    ports:
      - "8091:8080"
    volumes:
      - ${DATA_FOLDER}/rosetta/logs:/data/logs
    command: --port 8080 --observer=10.0.0.10
    networks:
      elrond-rosetta:
        ipv4_address: 10.0.0.21

  rosetta-offline:
    image: ${ROSETTA_IMAGE}
    ports:
      - "8092:8080"
    volumes:
      - ${DATA_FOLDER}/rosetta-offline/logs:/data/logs
    command: --port 8080 --offline --observer=http://nowhere.localhost.local
    networks:
      elrond-rosetta:
        ipv4_address: 10.0.0.22

networks:
  elrond-rosetta:
    ipam:
      config:
        - subnet: 10.0.0.0/24
