version: '3'

services:
  observer:
    image: ${OBSERVER_IMAGE}
    ports:
      - "8080:8080"
      - "10000:37373"
    volumes:
      - ${DATA_FOLDER}/node-${OBSERVED_SHARD}/logs:/data/logs
      - ${DATA_FOLDER}/node-${OBSERVED_SHARD}/db:/data/db
      - ${KEYS_FOLDER}:/keys
    command: --destination-shard-as-observer=${OBSERVED_SHARD} --validator-key-pem-file=/keys/${OBSERVED_SHARD}.pem
    networks:
      elrond-rosetta:
        ipv4_address: 10.0.0.10

  rosetta:
    image: ${ROSETTA_IMAGE}
    ports:
      - "8091:8080"
    volumes:
      - ${DATA_FOLDER}/rosetta/logs:/data/logs
    command: --port 8080 --observer-http-url=http://10.0.0.10:8080 --observer-pubkey=${OBSERVER_PUBKEY} --chain-id=${CHAIN_ID} --num-shards=${NUM_SHARDS} --observer-actual-shard=${OBSERVED_SHARD} --genesis-block=${GENESIS_BLOCK} --genesis-timestamp=${GENESIS_TIMESTAMP} --native-currency=${NATIVE_CURRENCY}
    networks:
      elrond-rosetta:
        ipv4_address: 10.0.0.21

  rosetta-offline:
    image: ${ROSETTA_IMAGE}
    ports:
      - "8092:8080"
    volumes:
      - ${DATA_FOLDER}/rosetta-offline/logs:/data/logs
    command: --port 8080 --offline --observer-http-url=http://nowhere.localhost.local  --chain-id=${CHAIN_ID} --num-shards=${NUM_SHARDS} --observer-actual-shard=${OBSERVED_SHARD} --genesis-block=${GENESIS_BLOCK} --genesis-timestamp=${GENESIS_TIMESTAMP} --native-currency=${NATIVE_CURRENCY}
    networks:
      elrond-rosetta:
        ipv4_address: 10.0.0.22

networks:
  elrond-rosetta:
    ipam:
      config:
        - subnet: 10.0.0.0/24
