# GeneralSettings section of the proxy server
[GeneralSettings]
# ServerPort is the port used for the web server. The frontend will connect to this port
ServerPort = 7950

   # RequestTimeoutSec represents the maximum number of seconds a request can last until throwing an error
   RequestTimeoutSec = 10

   # HeartbeatCacheValidityDurationSec represents the maximum number of seconds the heartbeat cache data is valid before it
   # should be updated
   HeartbeatCacheValidityDurationSec = 25

   # ValStatsCacheValidityDurationSec represents the maximum number of seconds the validator statistics cache data is valid
   # before it should be updated
   ValStatsCacheValidityDurationSec = 60

   # BalancedObservers - if this flag is set to true, then the requests will be distributed equally between observers.
   # Otherwise, there are chances that only one observer from a shard will process the requests
   BalancedObservers = true

   # BalancedFullHistoryNodes - if this flag is set to true, then the requests will be distributed equally between full history nodes.
   # Otherwise, there are chances that only one full history node from a shard will process the requests
   BalancedFullHistoryNodes = true

   # FaucetValue represents the default value for a faucet transaction. If set to "0", the faucet feature will be disabled
   FaucetValue = "0"

[AddressPubkeyConverter]
    #Length specifies the length in bytes of an address
    Length = 32

    # Type specifies the type of public keys: hex or bech32
    Type = "bech32"

[Marshalizer]
   Type = "gogo protobuf"

[Hasher]
   Type = "blake2b"

# List of Observers. If you want to define a metachain observer (needed for validator statistics route) use
# shard id 4294967295
[[Observers]]
   ShardId = 0
   Address = "http://127.0.0.1:8081"

[[Observers]]
   ShardId = 1
   Address = "http://127.0.0.1:8082"

[[FullHistoryNodes]]
   ShardId = 0
   Address = "http://127.0.0.1:8081"

[[FullHistoryNodes]]
   ShardId = 1
   Address = "http://127.0.0.1:8082"
