# GeneralSettings section of the proxy server
[GeneralSettings]
   # ServerPort is the port used for the web server. The frontend will connect to this port
   ServerPort = 8079
   # Interval in seconds to re-read the config file
   CfgFileReadInterval = 60

[[Observers]]
   ShardId = 0
   Address = "127.0.0.1:8080"

[[Observers]]
   ShardId = 1
   Address = "127.0.0.1:8081"
